[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "process_tracking"
version = "0.1.0"
description = "A tracking application that logs scan events for samples and processes."
readme = "README.md"
requires-python = "==3.13.*"
authors = [
    { name="Rajiv Daxini", email="Rajiv.Daxini@nrel.gov" }
]
dependencies = []

[project.optional-dependencies]
build = ["pyinstaller"]

[tool.setuptools.packages.find]
where = ["scripts"]
