[tox]
envlist = py310, py311, py312, py313

[testenv]
deps =
    pytest

commands =
    pytest

base_python =
    py310: C:\Users\rdaxini\AppData\Local\anaconda3\envs\py310\python.exe
    py311: C:\Users\rdaxini\AppData\Local\anaconda3\envs\py311\python.exe
